name: gfx-rs
markdown: redcarpet
highlighter: rouge
github: https://www.github.com/gfx-rs
about: The gfx-rs documentation and blog.
urls:
    - text: github
      url: https://github.com/gfx-rs/gfx-rs
